version: '3'
services:

  front:
    build:
      context: .
      dockerfile: front/DockerFile
    ports:
      - 3000:3000
    restart: always
    environment:
      PUBLIC_API_URL: 127.0.0.1:8080

  back:
    build:
      context: .
      dockerfile: back/DockerFile
    environment:
      DB_URL: db:5432/lab4_web
      DB_USERNAME: stepan
      DB_PASSWORD: postgres
    ports:
      - 8080:8080
    restart: always

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=stepan
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lab4_web
    restart: always

